spring.application.name=api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/stackburguer}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}

spring.datasource.driver-class-name=org.postgresql.Driver


# Isso aqui cria as tabelas no banco sozinho baseando se no seu Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Token Config
api.security.token.secret=${JWT_SECRET:ce3ccdabbe9a2bf4d9333f45d215990b}

#Stripe config
stripe.api.key=${STRIPE_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

#Config do S3
aws.s3.bucket=stackburguer-uploads-kauavidal

aws.accessKeyId=${AWS_ACCESS_KEY_ID}

aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}

aws.region=sa-east-1

spring.mvc.static-path-pattern=/files/**
spring.web.resources.static-locations=file:./uploads/,classpath:/static/

#Config de Email
admin.email=admin@stackburguer.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kauakauavidalpc@gmail.com
# Aqui vai a senha de aplicativo, nao a sua senha normal do Gmail
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_TOKEN}
twilio.whatsapp.number=whatsapp:+14155238886


#URLS
url.front.end=${URL_FRONT_END:http://localhost:5173}
url.s3.category=${URL_API_CATEGORY:http://localhost:8080/category-file/}
url.api.product=${URL_API_PRODUCT:http://localhost:8080/product-file/}
url.s3.bucket=https://%s.s3.%s.amazonaws.com/%s